services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - redis
      - qdrant

  worker:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["pnpm", "dev:worker"] 
    env_file:
      - ./.env
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - redis
      - qdrant
      - server

  redis:
    image: redis
    ports:
      - "6379:6379"

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
